//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel
    {
        public int personelid { get; set; }
        public string personelad { get; set; }
        public string personelkulad { get; set; }
        public string personelsifre { get; set; }
    }
}
