//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rapor1
    {
        public int rid { get; set; }
        public string kisiad { get; set; }
        public string kisibilgi { get; set; }
        public string kisibas { get; set; }
        public string kisibit { get; set; }
    }
}
