//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ogrenci
    {
        public int oid { get; set; }
        public string oadı { get; set; }
        public string ono { get; set; }
        public string obolum { get; set; }
        public Nullable<int> okredi { get; set; }
        public string odurum { get; set; }
    }
}
