//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_idare
    {
        public int pid { get; set; }
        public string perad { get; set; }
        public string perbolum { get; set; }
        public string perbas { get; set; }
        public string perbit { get; set; }
    }
}
